services: 
  frontend:
    build:
      context: ./frontend
    restart: on-failure
    image: pavel5926/devel-frontend:latest
    ports:
      - "30173:5173"
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_HMR_HOST=127.0.0.1
      - VITE_API_BASE_HOST=127.0.0.1
    volumes:
      - ./frontend/src:/frontend/src
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .
    networks:
      - itmo_devops_net

  backend:
    build:
      context: ./backend
    restart: on-failure
    image: pavel5926/devel-backend:latest
    ports:
      - "30070:8070"
    volumes:
      - ./backend/src:/backend/src
    depends_on:
      - mongo
    networks:
      - itmo_devops_net

  mongo:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: pavel
      MONGO_INITDB_ROOT_PASSWORD: popov
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - itmo_devops_net

  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    ports:
      - "30572:5672"
      - "30172:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: pavel
      RABBITMQ_DEFAULT_PASS: popov
    networks:
      - itmo_devops_net

volumes:
  mongo_data:
  rabbitmq_data:

networks:
  itmo_devops_net:
    driver: bridge