services: 
  frontend:
    build:
      context: ./frontend
    restart: on-failure
    ports:
      - "5173:5173"
    volumes:
      - frontend_src:/frontend/src
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .
    networks:
      - itmo_devops_net

  backend:
    build:
      context: ./backend
    restart: on-failure
    ports:
      - "8070:8070"
    volumes:
      - backend_src:/backend/src
    depends_on:
      - mongo
    networks:
      - itmo_devops_net

  mongo:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: pavel
      MONGO_INITDB_ROOT_PASSWORD: popov
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - itmo_devops_net


volumes:
  frontend_src:
  backend_src:
  mongo_data:

networks:
  itmo_devops_net:
    driver: bridge