#cloud-config
users:
  - name: parus
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBpqD24HB1dMucavJaYMc6W5Fj8WuD9Btg0GF5b9aGLU pashafizmat1@gmail.com
