apiVersion: batch/v1
kind: CronJob
metadata:
  name: check-new-frontend-image
  namespace: default
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cronjob-service-account
          containers:
          - name: check-new-image
            image:  manusant/curl-jq
            command:
            - /bin/bash
            - -c
            - |
              apt-get update && apt-get install -y curl jq && apt-get clean
              DOCKER_REPO="pavel5926/devel-frontend"
              DEPLOYMENT_NAME="frontend"
              NAMESPACE="default"

              if ! kubectl get deployment "$DEPLOYMENT_NAME" -n "$NAMESPACE" > /dev/null 2>&1; then
                echo "Error: Deployment '$DEPLOYMENT_NAME' not found in namespace '$NAMESPACE'!"
                exit 1
              fi

              CURRENT_TAG=$(kubectl get deployment "$DEPLOYMENT_NAME" -n "$NAMESPACE" \
                -o jsonpath='{.spec.template.spec.containers[0].image}' | cut -d':' -f2)

              LATEST_BUILD_TAG=$(curl -s "https://hub.docker.com/v2/repositories/$DOCKER_REPO/tags/?page_size=100" | \
                jq -r '.results[] | select(.name | startswith("build-")) | [.name, .last_updated] | @tsv' | \
                sort -k2 -r | \
                head -n1 | \
                cut -f1)


              if [ -z "$LATEST_BUILD_TAG" ]; then
                echo "Error: No build-* tags found in repository!"
                exit 1
              fi


              if [ "$LATEST_BUILD_TAG" != "$CURRENT_TAG" ]; then
                echo "New build tag detected: $LATEST_BUILD_TAG (was $CURRENT_TAG). Updating..."
                kubectl set image deployment/"$DEPLOYMENT_NAME" \
                  -n "$NAMESPACE" \
                  "$(kubectl get deployment "$DEPLOYMENT_NAME" -n "$NAMESPACE" -o jsonpath='{.spec.template.spec.containers[0].name}')"="$DOCKER_REPO:$LATEST_BUILD_TAG"
              else
                echo "No new build tags. Current: $CURRENT_TAG"
              fi
          restartPolicy: OnFailure
