spring.application.name=backend
server.port=8070
spring.data.mongodb.uri=mongodb://pavel:popov@127.0.0.1:27017
spring.data.mongodb.database=LogEntryStorage
management.endpoints.web.exposure.include=prometheus
management.metrics.export.prometheus.enabled=true