name: LogEntryCI

on:
  push:
    branches:
      - sonarqube_integration
  pull_request:
    branches:
      - sonarqube_integration

jobs:
  # build:
  #   runs-on: ubuntu-22.04

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Install backend dependencies
  #       uses: actions/setup-java@v3
  #       with:
  #         distribution: 'temurin'
  #         java-version: '21'
      
  #     - name: Install Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'
  
  #     - name: Install frontend dependencies
  #       run: cd frontend && npm install

  #     - name: Build backend
  #       run: cd backend/ && ./gradlew build -x test --no-daemon
      
  #     - name: Build frontend
  #       run: cd frontend/ && npm run build --if-present

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install backend dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Tests backend
        run: cd backend/ && ./gradlew test --info --no-daemon

      - name: Tests frontend
        run: cd frontend && npm test -- --run

  sonarqube_scan:
    name: sonar scan
    runs-on: ubuntu-22.04
    needs: test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: SonarQube Scan Backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION_KEY: ${{ secrets.SONAR_ORGANIZATION_KEY }}
        run: |
          cd backend
          ./gradlew jacocoTestReport sonar

      - name: Check Coverage Percentage
        run: |
          cd backend
          ./gradlew extractCoverage
